import { useRouter } from 'next/router';
import * as React from 'react';
import Head from 'next/head';
import NextLink from 'next/link';

import { CoreLayout } from '@/layouts/core/CoreLayout';
import { Stats } from '@/components/Stats';
import { Coin } from '@/components/Coin';
import * as Breadcrumbs from '@/components/system/Breadcrumbs';

import { FullCoinInformation } from '@/modules/cryptocurrencies/api';

const CoinPage = () => {
  const router = useRouter();
  const { coinId } = router.query;

  const [coin, setCoin] = React.useState<FullCoinInformation>();

  React.useEffect(() => {
    fetch(`/api/cryptocurrencies/${coinId as string}`)
      .then((data) => data.json())
      .then((data) => setCoin(data as FullCoinInformation))
      .catch((error) => console.log(error));
  }, [coinId]);

  return (
    <CoreLayout>
      <Head>
        <title>Cryptocurrencies | {coin?.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Breadcrumbs.Root>
        <Breadcrumbs.Item>
          <NextLink href="/cryptocurrencies" passHref>
            <Breadcrumbs.Link>
              Cryptocurrencies
            </Breadcrumbs.Link>
          </NextLink>
        </Breadcrumbs.Item>

        <Breadcrumbs.Separator>/</Breadcrumbs.Separator>

        <Breadcrumbs.Item>
          <NextLink href="/cryptocurrencies/coins" passHref>
            <Breadcrumbs.Link>
              Coins
            </Breadcrumbs.Link>
          </NextLink>
        </Breadcrumbs.Item>

        <Breadcrumbs.Separator>/</Breadcrumbs.Separator>

        <Breadcrumbs.Item>{coin?.name}</Breadcrumbs.Item>
      </Breadcrumbs.Root>

      <Coin
        coin={coin?.name ?? ''}
        value={coin?.price ?? ''}
        rank={coin?.rank ?? 0}
        change={coin?.change ?? ''}
        iconUrl={coin?.iconUrl ?? ''}
      />
      <Stats rate1="0.50" rate2="-0.76" rate3="8.75" />
    </CoreLayout>
  );
};

export default CoinPage;
