import { useRouter } from 'next/router';
import Head from 'next/head';
import NextLink from 'next/link';

import { CoreLayout } from '@/layouts/core/CoreLayout';
import { Stats } from '@/components/Stats';
import { Coin } from '@/components/Coin';
import * as Breadcrumbs from '@/components/system/Breadcrumbs';

const CoinPage = () => {
  const router = useRouter();
  const { coinName } = router.query;

  return (
    <CoreLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Breadcrumbs.Root>
        <Breadcrumbs.Item>
          <NextLink href="/cryptocurrencies" passHref>
            <Breadcrumbs.Link>
              Cryptocurrencies
            </Breadcrumbs.Link>
          </NextLink>
        </Breadcrumbs.Item>

        <Breadcrumbs.Separator>/</Breadcrumbs.Separator>

        <Breadcrumbs.Item>
          <NextLink href="/cryptocurrencies/coins" passHref>
            <Breadcrumbs.Link>
              Coins
            </Breadcrumbs.Link>
          </NextLink>
        </Breadcrumbs.Item>

        <Breadcrumbs.Separator>/</Breadcrumbs.Separator>

        <Breadcrumbs.Item>{coinName}</Breadcrumbs.Item>
      </Breadcrumbs.Root>

      <Coin
        coin="Ethereum"
        value="2,400.80"
        rank={2}
        change="0.50"
        iconUrl="https://cdn.coinranking.com/Sy33Krudb/btc.svg"
      />
      <Stats rate1="0.50" rate2="-0.76" rate3="8.75" />
    </CoreLayout>
  );
};

export default CoinPage;
