import Head from 'next/head';

import { CoreLayout } from '@/layouts/core/CoreLayout';
import { Stats } from '@/common/components/Stats';

const Home = () => {
  return (
    <CoreLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Stats rate1="0.50" rate2="-0.76" rate3="8.75" />
    </CoreLayout>
  );
};

export default Home;
