import Head from 'next/head';

import { CoreLayout } from '@/layouts/core/CoreLayout';

const Home = () => {
  return (
    <CoreLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </CoreLayout>
  );
};

export default Home;
