import * as React from 'react';
import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { useQuery, QueryClient, dehydrate } from 'react-query';

import { CoreLayout } from '@/layouts/core/CoreLayout';
import { CoinsTable } from '@/components/CoinsTable';

import { REACT_QUERY_STATE_PROP_NAME, ReactQueryState } from '@/modules/rquery/react-query';
import { FetchAllCoinsResponse, fetchAllCoins } from '@/modules/cryptocurrencies/api/coins.service';

export const getServerSideProps: GetServerSideProps<ReactQueryState> = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery('coins', () => fetchAllCoins(0, 10));

  return {
    props: {
      [REACT_QUERY_STATE_PROP_NAME]: dehydrate(queryClient),
    },
  };
};

const Home = () => {
  const [page, setPage] = React.useState(0);

  const query = useQuery(['coins', page], async () => {
    const data = await fetch(`http://localhost:3000/api/cryptocurrencies/coins?limit=10&offset=${page * 10}`);
    const coins = await data.json() as FetchAllCoinsResponse['data'];

    return coins;
  }, {
    keepPreviousData: true,
  });

  return (
    <CoreLayout>
      <Head>
        <title>Cryptocurrencies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CoinsTable coins={query.data?.coins} />
      <div>
        <button
          type="button"
          onClick={() => setPage((prevPage) => prevPage - 1)}
          disabled={page === 0}
        >
          prev
        </button>
        <button
          type="button"
          onClick={() => setPage((prevPage) => prevPage + 1)}
        >
          next
        </button>
      </div>
    </CoreLayout>
  );
};

export default Home;
